version: "3.7"

services:
  nginx-nchan:
    image: weseek/nginx-nchan
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
  app:
    build:
      context: .
    container_name: websocket_go
    ports:
      - 8080:8080
